#Remote DataBase
#=================================
# Server
#=================================
server.port=8080
#=================================
# Mongo DB
#=================================
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true
#=================================
# JWT
#=================================
api.security.key.secret = ${JWT_SECRET_KEY}