spring.application.name=vacinas-api
#Remote DataBase
#spring.mongodb.uri=mongodb+srv://vacina-api:vacina-api-180906@cluster0.xikahpj.mongodb.net/?appName=Cluster0
#Local DataBase
spring.mongodb.uri=mongodb://localhost:27017/
spring.mongodb.database=vacinasdb
server.address=0.0.0.0
server.port=8080
spring.data.mongodb.auto-index-creation=true


api.security.key.secret = ${JWT_SECRET_KEY : my-secret-key-api}