#Local DataBase
#=========================
# Server
#=========================
server.port=8080
server.address=0.0.0.0
#=========================
# Mongo DB
#=========================
spring.mongodb.uri=mongodb://localhost:27017/
spring.mongodb.database=vacinasdb
spring.data.mongodb.auto-index-creation=true
#=========================
# JWT
#=========================

api.security.key.secret = ${JWT_SECRET_DEV_KEY : my-secret-key-api}