spring.application.name=vacinas-api

spring.mongodb.uri=mongodb://localhost:27017/vacinasdb
spring.mongodb.database=vacinasdb
server.port=8080
spring.data.mongodb.auto-index-creation=true


api.security.key.secret = ${JWT_SECRET_KEY : my-secret-key-api}